version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dala_note
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  # .NET API will be added when built
  # ai-service will be added when built  
  # export-service will be added when built

volumes:
  postgres_data: